### PR TITLE
restructured process. voxel for all clouds, no more use of PCL2 only …

### PR DESCRIPTION
**Pull request by GustavSandstroem**
…<XYZRGB> is RGB needed? remove for future? . separated process from object detecion. returns centroids. there is markers for debugg. Comment out when real run. use rdy=true for workaround not use calibration. A LOT OF UPDATES!!

### CODE REVIEW

**Comment by Jinxit** [comment]
fix lag pls

(OK)

**Comment by goncacp** [comment]
ok

**Comment by Thrasi** [comment]
OK, but just to be a dick:  Why not call the variable rdy -> ready
And a couple of questions:

The tilt angle is then arccos(abs(b))?

Process.cpp preprocesses the pointcloud before we detect the objects with objectdetection.cpp?

**Comment by Jinxit** [comment]
Tilt angle: Yes.

Process: Yes, it rotates and filters the cloud so we only get points between 40-80cm in depth and > 1cm in height.

**Pull request merged**
